### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by CPLANAS1985** [wilmsn/myGAPPS#1]
No matter if I choose YES or NO... The result is the same... Can someone look at this please???

![mygapps errors](https://cloud.githubusercontent.com/assets/26356066/23829431/1319e832-06bf-11e7-8205-ddd18e34723a.png)

**Comment by wilmsn** [comment]
Looks like you are running out of memory with java. Open the script and look for "java -Xmx512m" and try to replace it to "java -Xmx1024m"
Hope it helps.

**Comment by nickm324** [comment]
didnt help
